[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix admin"
]

[phases.build]
cmds = [
  "npm run build --prefix admin"
]

[start]
cmd = "npm start --prefix backend"
